export const classicRunawayPrompt = `WHAT TO BUILD
Build a portable React + TypeScript moving button named ClassicRunaway. Its optional prop is switches?: { onClick?: boolean; anxious?: boolean; talkative?: boolean }; every missing value is false. Use it as <ClassicRunaway switches={{ onClick: false, anxious: true, talkative: true }} />. Keep the component and its plain CSS self-contained, with no application-specific imports.

Reproduce the behavior exactly as specified; do not adjust thresholds, timings, or interaction.

MARKUP AND SEMANTICS
- Render a specimen as a vertical flex layout containing a position-relative arena and a readout below it.
- Center one native type="button" absolutely in the arena. Its initial label is “Continue” followed by an aria-hidden right-arrow icon.
- The readout is a paragraph with role="status", aria-live="polite", and aria-atomic="true", containing “Presses” and the integer count.
- Do not remove native button focus or keyboard activation.

BEHAVIOR
- Track moves and presses from 0. Keep refs for the arena and button, and run pointer motion in requestAnimationFrame from an effect. Observe both elements with ResizeObserver.
- Measure button half-width and half-height. Its center may move within the arena minus exactly 12px wall clearance. If a button is larger than an axis, pin that axis to its midpoint.
- In hover mode, hop whenever the pointer’s Euclidean gap from the destination button rectangle is strictly less than TRIGGER = 56px. Measure against the current destination, not the animated position. Listen for pointermove and pointerdown on window, not the arena, storing clientX and clientY and converting them to arena-relative offsets each time they are read; clear the pointer on pointerleave of the document element. Re-run the same check with the stored pointer when a flight lands and after a resize, so a still pointer within 56px sends it again.
- In click mode, proximity does nothing. A pointerdown on the button always hops in either mode. Mark that press as dodged so the click generated by the same press is discarded; clear the marker on pointerup or pointercancel through a zero-millisecond window timeout. Keyboard clicks and any click not paired with that dodged pointer press increment Presses.
- For a hop, take SAMPLES = 8 uniformly random candidate centers inside the bounds. Among candidates at least MIN_HOP = 90px from the previous destination, choose the one farthest from the pointer. If none travels 90px, choose the farthest candidate regardless. Increment Moves once per hop.
- Animate x and y with semi-implicit Euler springs: STIFFNESS = 900, damping ratio = 0.55, DAMPING = 33, timestep substeps no larger than 1/240 second, frame delta clamped to between 0 and 0.05 second (a wake from a pointer event can stamp the start time after the next frame's timestamp), the loop kept running until the body sits exactly on its destination as well as at zero velocity, position settle epsilon 0.05 and velocity epsilon 0.5. The motion is underdamped, overshooting roughly 12%, peaking near 125ms, and settling near 250ms.
- Track the normalized direction of each flight. When the animated body first passes the destination along that direction, kick a separate squash spring with velocity -min(arrivalSpeed / 220, 11). Squash stiffness is 1600, damping ratio 0.4, damping 32, value epsilon 0.0005, and velocity epsilon 0.005.
- Stretch along current velocity by min(speed / 6000, 0.22). Apply squash along the flight direction. Compose transforms so neither directional effect rotates the label; the base transform remains translate(-50%, -50%) followed by the center offset.
- When anxious is true and reduced motion is false, calculate closeness = max(0, 1 - gapFromDestinationEdge / 150), then amount = closeness * sqrt(closeness). Every frame, add independent random x and y offsets in ±3px times amount and a random tilt in ±0.035 radians times amount. Wake the loop immediately when anxious becomes enabled even if the pointer is still.
- When talkative is true and at least one move occurred, replace the label after each move by cycling exactly through: “haha”, “almost”, “psych”, “try again”, “peace”, “OwO”, “nope”, “too slow”, “so close”, “bye”. Omit the arrow for these labels. When talkative is false, show “Continue” and the arrow.
- On resize or a talkative width change, remeasure bounds, clamp the destination, and if clamping changed it, place the animated body there with zero x/y velocity.
- Under prefers-reduced-motion, every hop relocates immediately and disables spring flight, stretch, landing squash, and shiver. All interaction rules and counting remain unchanged.

STYLING
- The specimen stretches to its container, is a vertical flex layout with 12px gap, min-width 0, and color #282824. The arena flexes to fill available height, has position relative, min-height 160px, and touch-action manipulation.
- The button is top 50%, left 50%, initially translate(-50%, -50%), inline-flex centered with 10px gap, min-height 39px, padding 8px 16px, 1px transparent border, 5px radius, background #30312b, text #fafaf6, 12px medium inherited sans-serif, line-height 1.5, nowrap, pointer cursor, will-change transform, and touch-action manipulation.
- Button hover background is #4d5142. Focus-visible outline is 2px solid #667251 with 3px offset. The arrow is 12px square with a 1.25px currentColor stroke.
- The readout is a flex row spaced apart, margin 0, 11px, color #6b6b63. The count is #282824 in a monospace stack with tabular numerals.
- Use a 150ms ease background transition for the button and remove it under reduced motion.

DONE WHEN
- Hover and click trigger modes differ exactly as specified, and a pointer press that causes a hop never increments Presses.
- Random destination selection, 12px wall clearance, spring integration, stretch, landing squash, anxious falloff, label cycle, resize clamping, and reduced-motion behavior all preserve the stated constants.
- The button remains a native keyboard-operable button and Presses is announced politely and atomically.
`;
