export const thinkingPrompt = `WHAT TO BUILD
Build a portable React + TypeScript file upload readout named Thinking. It takes no props and is used as <Thinking />. Keep the component and its plain CSS self-contained, with no application-specific imports.

Reproduce the behavior exactly as specified; do not adjust thresholds, timings, or interaction.

MARKUP AND SEMANTICS
- Render one bordered card. At the top, a row with the file name “report-final-FINAL.pdf” on the left and “4.2 MB” on the right.
- Below it, a large aria-hidden paragraph showing the percentage with one decimal and a percent sign, e.g. “0.0%”.
- Below that, a track div with role="progressbar", aria-label="Upload progress", aria-valuemin 0, aria-valuemax 100, aria-valuenow equal to the displayed percentage, and aria-valuetext equal to the one-decimal text with a percent sign, followed by “, thinking” during a thinking phase (e.g. “61.2%, thinking”) and “, stopped” at the limit. Inside it, two divs: a high-water band, then the fill on top of it.
- Below the track, a thought row. It is empty until the first thinking phase ends. After that it holds a native <details> element whose <summary> reads “Thought for N seconds”, where N is the length of the most recent thinking phase. Its content is a list: every scripted line of that pause, in order, then a final item “Reached X%. Resumed at Y%.” with both values to one decimal. Each resumed thought replaces the previous one and starts closed. The final check replaces the content with its lines and “Stopped at 95.0%.”, preserving the disclosure’s open state.
- Below the thought row, a row with a status slot on the left and a single type="button" on the right.
- The status slot holds a paragraph with role="status". Idle: “Ready to upload”. Working: the status paragraph reads “About N seconds remaining” with the burst's starting estimate and is visually hidden, so it is announced once per burst; a second aria-hidden paragraph beside it shows the visible countdown in the same wording (“About 1 second remaining” in the singular). At the limit: “Upload stopped”. While thinking it announces the current scripted line and is visually hidden (position absolute, 1px by 1px, padding 0, margin -1px, overflow hidden, clip rect(0, 0, 0, 0), white-space nowrap, border 0). A second aria-hidden paragraph shows the same line with shimmer. Announce each new line, never individual progress ticks.
- The button has no visible text. While idle or at the limit it has aria-label="Upload" and shows an aria-hidden 16px up-arrow SVG (viewBox 0 0 16 16, path "M8 13V3M3.5 7.5 8 3l4.5 4.5", no fill, currentColor stroke 1.75 wide, round caps and joins). While working or thinking it has aria-label="Stop" and shows an aria-hidden 10px square. It is the same button element in every state, so focus is preserved.
- Below everything, a div with role="status" for notices, hidden while empty. Once the highest percentage is at least 85, show a warning paragraph: “Usage credits remaining: N%.”, a line break, then “Your usage credits are running low.” N is 10, except during the sixth burst (the climb after “Compacting conversation”) once percent >= (from + 95) / 2, where it is 5. During the final check the credits shown are 5, 3, and 1 percent, respectively, for its three lines. At the limit show “Usage credits remaining: 0%.”, a line break, then “Usage limit reached. Upgrade your plan or purchase more credits to continue.”

BEHAVIOR
- Use Math.random for every random draw. between(min, max) = min + (max - min) * random. wholeBetween(min, max) = min + Math.floor(random * (max - min + 1)). tenths(v) = Math.round(v * 10) / 10.
- The script: six pauses, each a fixed list of lines, shown in this order:
  1. “Thinking”
  2. “Thinking”, “Reconsidering upload strategy”
  3. “Thinking”, “Web search: how to upload files”, “Reading result 1 of 2,340,000”, “Reading result 2 of 2,340,000”
  4. “Loading /upload skill”, “Calling subagents”, “Waiting for subagents”
  5. “Thinking”, “Compacting conversation”
  6. “Estimating remaining work”, “Remaining work: 5%”, “Checking available credits”
- Peak bands, one per burst before a pause: [38, 48], [55, 63], [30, 38], [58, 66], [86, 90], [95, 95]. planPeak(cycle) = tenths(between(band[0], band[1])) for cycle 0–5, and 95 as a fallback. The final pause ends the run; no seventh burst occurs.
- State while running: phase (working, thinking, or limit), percent, from (where the current burst began), peak, highest, cycle (bursts completed), estimate (seconds the current burst started with), ticks (working ticks in the current burst), since (performance.now() when the current thinking phase began), line (index into the current pause's script), and the last thought. Null while idle.
- Upload starts a run: phase working, percent 0, from 0, highest 0, cycle 0, estimate 3, ticks 0, peak = planPeak(0). Stop returns to idle from working or thinking: 0.0%, empty thought row, no notice, no timers. At the limit the button is Upload again and starts a fresh run from the first pause.
- Working: every 150ms (a setInterval that runs only in the working phase), if percent < peak, percent = Math.min(tenths(percent + between(1, 3)), peak, 95) highest = Math.max(highest, percent), and ticks increases by 1. The visible countdown is Math.max(1, estimate - Math.floor(ticks * 150 / 1000)). Reaching 95 does not yet stop the run. Once percent has reached its peak, the next tick switches to thinking with since = performance.now() and line 0.
- Thinking: use one setTimeout for each line, cleaned up on line/phase change. Per-line durations in milliseconds by pause: [1600], [1200, 1600], [1200, 1800, 1300, 1300], [1200, 1200, 2600], [1200, 2000], [1400, 1600, 2400]. Advance when the current line’s duration expires. All scripted pauses total 23.6 seconds.
- After pauses 1, 3, and 4, resume at tenths(percent - between(0.25, 0.55) * (percent - from)). After pause 2 (“Reconsidering upload strategy”), resume at 0. After pauses 1–4, increase estimate by wholeBetween(2, 5). After pause 5 (“Compacting conversation”), resume at tenths(between(21, 28)) and reset estimate to 3. For these five resumptions: record measured seconds = Math.round((performance.now() - since) / 1000), the script, the reached percentage and resumed percentage; set percent and from to the resumed percentage, peak = planPeak(cycle + 1), increment cycle, reset ticks to 0, and enter working. Never lower highest.
- During pause 6, hold progress at 95.0%. Each line consumes credits: show 5%, then 3%, then 1%. When “Checking available credits” has shown for 2000ms, enter limit directly, show 0% credits, stop all timers, and record this pause with measured duration, its script, reached 95, and no resumed value. Never return to working after this check.
- The disclosure reports the measured seconds, not the planned ones, so it stays accurate if timers are delayed.
- Each band starts above the previous band, or above 0 after the second pause, and every resume except the second and fifth is at or above the burst's start, so every run takes exactly six pauses, drops to 0.0% after the second pause while the band stays at the highest point, crosses 85 during the fifth burst, falls to the twenties after the fifth pause while the band stays at the highest point, climbs back to 95, and holds there through the sixth pause until credits reach zero. It never displays 100.
- The high-water band is drawn with transform scaleX(highest / 100) and the fill with scaleX(percent / 100), both from their left edges; when the percentage drops, the band stays at the highest point reached.
- The thinking line shimmers: a horizontal gradient clipped to the text sweeps across it every 1800ms, linear, infinite.
- Under prefers-reduced-motion: reduce, remove the fill, band, button, and disclosure-marker transitions, and replace the shimmer with plain text in the muted color.
- Clear every interval and timeout on phase change, Stop, and unmount.

STYLING
- Colors are given as light-dark(light, dark) pairs and resolve against the page's color-scheme; if the host page does not set one, set color-scheme: light dark on :root.
- The card is width 100%, max-width 320px, centered, color light-dark(#282824, #e8e7e0), 1px solid light-dark(#deded6, #34342f) border, 6px radius, light-dark(#ffffff, #1a1a17) background, padding 18px 18px 16px.
- The file row is a baseline-aligned flex row, space-between, 12px gap, 13px type; the name is weight 500 and wraps anywhere. The size, the status, and the thinking line are 11px light-dark(#6b6b63, #9c9c91) with no margin.
- The percentage has margin 18px 0 8px, sans-serif 34px, line-height 1.1, letter-spacing -1.5px, tabular numerals.
- The track is position relative, 6px tall, overflow hidden, fully rounded, background light-dark(#ecece4, #2d2d28). The band is absolutely positioned over the whole track, inherits the radius, background light-dark(#bcc2b0, #5a6250). The fill is position relative, full height, inherits the radius, background light-dark(#54614a, #b6c2a2). Both use transform-origin left center and a 250ms linear transform transition.
- The thought row has min-height 26px and margin-top 8px, so the card does not grow when the first thought appears. The disclosure is 11px light-dark(#6b6b63, #9c9c91). The summary is an inline-flex row, centered, 6px gap, min-height 26px, 3px radius, pointer cursor, with the native marker hidden (list-style none and ::-webkit-details-marker display none). Its ::before is a right-pointing triangle drawn with borders (3.5px transparent top and bottom, 5px currentColor left) that rotates 90deg when open, with a 150ms ease transform transition. On hover the summary text is light-dark(#282824, #e8e7e0). Its focus-visible outline is 2px solid light-dark(#667251, #8e9c78) at 3px offset. The list has margin 4px 0 0, padding-left 11px, a 1px solid light-dark(#deded6, #34342f) left border, no bullets, and line-height 1.7.
- The shimmer background is linear-gradient(90deg, muted 0%, muted 35%, foreground 50%, muted 65%, muted 100%), where muted is light-dark(#6b6b63, #9c9c91) and foreground is light-dark(#282824, #e8e7e0), sized 250% 100%, clipped to the text with transparent text color, animating background-position from 100% 0 to 0 0.
- The bottom row is a centered flex row, space-between, 12px gap, 8px top margin. The status slot has min-width 0.
- The button is a 36px circle (inline-flex, centered, no padding, no border, flex none), background light-dark(#30312b, #e8e7e0), color light-dark(#fafaf6, #1a1a17), pointer cursor, with a 150ms ease background transition; hover background light-dark(#4d5142, #cdd1c2). The stop square has a 2px radius in currentColor. Focus-visible outline is 2px solid light-dark(#667251, #8e9c78) at 3px offset.
- Each notice paragraph has margin 14px 0 0, padding 8px 10px, a 1px solid border, 5px radius, 11px type, line-height 1.5. The warning is border light-dark(#ecd6a8, #4d3d1f), background light-dark(#fbf3e2, #2e2616), text light-dark(#7a4d0b, #e9c27a). The limit notice is border light-dark(#efc9c6, #55302d), background light-dark(#fbeceb, #301b1a), text light-dark(#8f2a24, #f0a39c).

DONE WHEN
- After the up-arrow button is pressed, the readout climbs by 1 to 3 points every 150ms to between 38 and 48%, and the visible status counts down from “About 3 seconds remaining” once a second, holding at “About 1 second remaining”, while the role=status paragraph keeps the starting estimate.
- Each pause shows and announces its script in order with the specified per-line timings. The first, third, and fourth resume with less progress and a higher estimate; after “Reconsidering upload strategy” progress resumes at 0.0% with a higher estimate. After “Compacting conversation” progress resumes between 21 and 28% and the estimate returns to “About 3 seconds remaining”.
- “Thought for N seconds” matches the pause's real length, lists that pause's script, and says where the upload resumed or stopped; the band holds the highest point reached.
- The credits warning appears during the fifth burst showing 10%, changes to 5% halfway through the climb after compaction, and during the sixth pause progress holds at 95.0% as credits fall 5 → 3 → 1 → 0; it then stops with the usage-limit notice and the button returns to Upload.
- The square button returns to 0.0% and “Ready to upload”, and the progressbar attributes track the display.
`;
